### ISSUE TITLE
introduce sdkPath API to analysis driver

### ISSUE THREAD

**Issue by pq** [pq/surveyor#29]
To support cases where clients need to customize SDK location, we could add an API like:

```dart
var driver = Driver.forArgs([packageFolder], sdkPath: myPath);
...
await driver.analyze();
```

**Comment by bwilkerson** [comment]
If clients need to be able to specify the sdk, then this should be added to `AnalysisContextCollection` rather than to have more packages reaching inside `src`.

@scheglov

**Comment by polina-c** [comment]
It would be great to avoid accessing src of the analyser, in order to provide path to SDK.

**Comment by scheglov** [comment]
I will update `AnalysisContextCollection` to include `sdkPath`.
